version: '3'

services: 
  frontend: 
    build: .
    environment: 
      - NODE_ENV=development
    volumes: 
      - ./:/usr/src/app
    command: sh -c 'cd frontend && yarn start'
    ports: 
      - '8000:4000'
    tty: true
